language: python
python:
  - "3.6"
install:
  - "pip install pipenv"
script:
  "cd xbbg/venv"
  "pipenv install"
  "pipenv shell"
  "cd .."
  "python -m xbbg.const all"
  "python -m xbbg.intervals all"
  "python -m xbbg.ccy_pair all"
  "python -m xbbg.assist all"
